# Makefile for life-nonblocking.cpp using mpicxx or mpicc

all: life-nonblocking

MPICXX = mpicxx
MPICXXFLAGS = -std=c++11 -O2

life-nonblocking: life-nonblocking.cpp
	$(MPICXX) $(MPICXXFLAGS) -o life-nonblocking $<

clean:
	rm -f life-nonblocking.o life-nonblocking
